In [3]:
# importing the library
# Here we are importing numpy package and giving it a name as "np". Whenever we want to use numpy, then use "np"
import numpy as np

In [9]:
a = np.array([1,2,3]) # 1-d array 

In [13]:
# printing the array
print(a)
a

[1 2 3]


array([1, 2, 3])

In [14]:
b = np.array([[1,2],[3,4]]) # 2-d array
print(b)
b

[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4]])

In [18]:
c = np.arange(11) # prints from 0 to 10
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
d = np.arange(1,11) # prints from 1 to 10
print(d)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
e = np.arange(1,11,2)
print(e)

[1 3 5 7 9]


In [22]:
f = np.arange(2,10,3)
print(f)

[2 5 8]


In [23]:
g = np.arange(10)
h = g.reshape(2,5) # Change the 1-d array into 2*5 matrix
print(h)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
i = h.reshape(5,2) # Change the 1-d array into 5*2 matrix( 5 rows and 2 columns)
print(i)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
print(i.shape) # The dimensions of the array

(5, 2)


In [28]:
print(i.ndim) # no.of dimensions of the array

2


In [29]:
print(i.dtype) # An object describing the type of the elements in the array

int32


In [31]:
print(i.itemsize) # The size in bytes of each element of the array (32/8)

4


In [32]:
print(i.size) # The total number of elements of the array

10


In [33]:
print(type(i)) # Returns the type of object

<class 'numpy.ndarray'>


In [36]:
np.zeros( (3,4) ) # creates an array of 3*4 with all zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros( (2,2) )

array([[0., 0.],
       [0., 0.]])

In [38]:
np.ones( (2,3), dtype=np.int16 ) #  creates an array of all ones. dtype can also be specified

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [39]:
np.ones( (4,2) )

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
np.empty( (3,3) )  # Creates an empty array. Note that the numbers are the elements at that location

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.94855038e-321],
       [8.70018274e-313, 2.22522596e-306, 2.56761491e-312]])

In [42]:
np.eye(3,3) # creates identity matrix of 3*3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(2,2) # creates identity matrix of 2*2

array([[1., 0.],
       [0., 1.]])

In [44]:
np.full((2,2),5) # Creates a matrix with the specified elements

array([[5, 5],
       [5, 5]])

In [45]:
np.full((3,2),7) # Creates a matrix with the specified elements

array([[7, 7],
       [7, 7],
       [7, 7]])

In [46]:
np.random.random((2,3)) # Creates a matrix with some random numbers

array([[0.32196955, 0.52272219, 0.85213127],
       [0.13773861, 0.91960921, 0.85441594]])

In [49]:
# creating two arrays
x = np.array([8,7,4,5])
y = np.arange(4)

In [50]:
# printing the two arrays
print(x)
print(y)

[8 7 4 5]
[0 1 2 3]


In [51]:
# Adding two arrays
print(x+y)

[8 8 6 8]


In [52]:
# subtraction of two arrays
print(x-y)

[8 6 2 2]


In [53]:
print(y**2) # Scalar multiplication(power)

[0 1 4 9]


In [54]:
print(x<5)

[False False  True False]


In [56]:
print(x[0]+y[3]) # adding first element in array-x and fourth element in array-y

11


In [57]:
# creating two 2-d arrays
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])

print(m)
print(n)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [58]:
print(m+n) # addition

[[ 6  8]
 [10 12]]


In [59]:
print(m-n) # subtraction

[[-4 -4]
 [-4 -4]]


In [60]:
print(m*n) # elementwise product

[[ 5 12]
 [21 32]]


In [61]:
print(m @ n)  # matrix product
print(m.dot(n)) # another matrix product
print(np.dot(m,n)) # another matrix product

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [62]:
z = np.arange(12).reshape(4,3)
print(z)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [63]:
print(z.sum()) # Addition of all elements in z

66


In [64]:
print(z.sum(axis=0)) # Note that axis=0 means column and axis=1 is row

[18 22 26]


In [65]:
print(z.sum(axis=1))

[ 3 12 21 30]


In [67]:
print(z.min(axis=1)) # Minimum element from each row
print(z.max(axis=1)) # Maximum element from each row

[0 3 6 9]
[ 2  5  8 11]


In [68]:
print(z.min(axis=0)) # Minimum element from each column
print(z.max(axis=0)) # Maximum element from each column

[0 1 2]
[ 9 10 11]


In [69]:
print(z.cumsum(axis=1)) # Cummulative sum of each row
print(z.cumsum(axis=0)) # Cummulative sum of each column

[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]
 [18 22 26]]


In [71]:
print(z.cumprod(axis=1)) # Cummulative product of each row
print(z.cumprod(axis=0)) # Cummulative product of each column

[[  0   0   0]
 [  3  12  60]
 [  6  42 336]
 [  9  90 990]]
[[  0   1   2]
 [  0   4  10]
 [  0  28  80]
 [  0 280 880]]


In [72]:
u=np.arange(5)
v=np.random.random(5)

print(u)
print(v)

[0 1 2 3 4]
[0.75502575 0.71508472 0.79723519 0.95795351 0.66344693]


In [74]:
print(u + v) # Elementwise sum; both produce the same array
print(np.add(u,v))

[0.75502575 1.71508472 2.79723519 3.95795351 4.66344693]
[0.75502575 1.71508472 2.79723519 3.95795351 4.66344693]


In [75]:
print(u - v) # Elementwise difference; both produce the same array
print(np.subtract(u, v))

[-0.75502575  0.28491528  1.20276481  2.04204649  3.33655307]
[-0.75502575  0.28491528  1.20276481  2.04204649  3.33655307]


In [76]:
print(u * v)# Elementwise product; both produce the same array
print(np.multiply(u, v))

[0.         0.71508472 1.59447038 2.87386052 2.65378771]
[0.         0.71508472 1.59447038 2.87386052 2.65378771]


In [77]:
print(u / v)# Elementwise division; both produce the same array
print(np.divide(u , v))

[0.         1.3984357  2.50867    3.131676   6.02911829]
[0.         1.3984357  2.50867    3.131676   6.02911829]


In [81]:
# Slicing a 1-D array
a=np.arange(5)**3

print(a)
print(a[2]) # Prints the element at index 2. i.e 3rd element of the array a
print(a[2:5]) # Prints the element from index 2 to index 3. Note that a[2:4] means elements from 2 upto 4 (But not including 4).
print(a[1:3]) # Note that this returns an array with 1 element. But a[2] returns a scalar element

[ 0  1  8 27 64]
8
[ 8 27 64]
[1 8]


In [82]:
# Slicing a 2-D array
a=np.arange(12).reshape(4,3) # Create an array "a" with numbers from 0 to 11.

print(a)
print(a[1:3]) # Prints second and third rows
print(a[1:3,1:2]) # from second and third rows, print second column
print(a[2,])# print 3rd row
print(a[:2],) # print 1st and 2nd row
print(a[:3,])# print 1st, 2nd and 3rd row
print(a[:3,:2])# from 1st , 2nd and 3rd row, print 1st and 2nd column 
print(a[:,2]) # from all rows, print 3rd column
print(a[2,:])# print 3rd row with all columns

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3 4 5]
 [6 7 8]]
[[4]
 [7]]
[6 7 8]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]
 [6 7]]
[ 2  5  8 11]
[6 7 8]


In [83]:
# Slicing 1-D array using -ve indexing
a=np.arange(10)

print(a)
print(a[-1]) # prints last element
print(a[-2]) # prints last but element
print(a[-5:-2]) # prints 5th ,6th and 7th element. i.e -5,-4,-3

[0 1 2 3 4 5 6 7 8 9]
9
8
[5 6 7]


In [84]:
# Slicing a 2=D using -ve indexing
a=np.arange(12).reshape(4,3)**2 

print(a)
print(a[-1,]) # Prints last row
print(a[-1,-1]) # print element at last row and last column
print(a[-3:-1,-2:]) # Note: -3 :-1 means 3rd row from last upto 1st row from last(exclusive) and -2: means 
                    #2nd column and 1st column from last.

[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
[ 81 100 121]
121
[[16 25]
 [49 64]]


In [85]:
# <--------------->

In [86]:
j = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Create an array "j"
j

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
b=j[:1,:1] # Use slicing to pull out the subarray consisting of 1st element in an array
b

array([[1]])

In [90]:
b[0] = 20

In [91]:
j  # Note that original array is changed

array([[20,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [92]:
# <--------------->

In [93]:
# <--------------->

In [94]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [96]:
# Select one element from each row of "a" using the indices in b.
a[np.arange(3),b]

array([1, 5, 9])

In [97]:
a[np.arange(3),b]+=10 # We have change one element from each row of a using the indices in b
a

array([[11,  2,  3],
       [ 4, 15,  6],
       [ 7,  8, 19]])

In [ ]:
# <--------------->

In [98]:
a=np.arange(12).reshape(4,3) # Create an array "a" with numbers from 0 to 11.
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [99]:
for i in a:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [100]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [101]:
# <-------------->

In [102]:
a=np.floor(10*np.random.random((3,4))) # Create a rondom 3*4 matrix.
a

array([[4., 6., 1., 6.],
       [8., 5., 1., 2.],
       [0., 5., 9., 4.]])

In [103]:
a.reshape(2,6)

array([[4., 6., 1., 6., 8., 5.],
       [1., 2., 0., 5., 9., 4.]])

In [104]:
a # Note that actual array is not changed

array([[4., 6., 1., 6.],
       [8., 5., 1., 2.],
       [0., 5., 9., 4.]])

In [105]:
a.resize(2,6)

In [106]:
a # The reshape function returns its argument with a modified shape, 
  # whereas the ndarray.resize method modifies the array itself:

array([[4., 6., 1., 6., 8., 5.],
       [1., 2., 0., 5., 9., 4.]])

In [107]:
# <------------>

In [112]:
o=np.arange(12).reshape(3,4)
print(o.ravel()) # function to flatten an array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [113]:
o.T # transpose of matrix

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [114]:
# Create 2 matrices

a=np.floor(10*np.random.random((2,2)))
print(a)

b=np.floor(10*np.random.random((2,2)))
print(b)

[[2. 2.]
 [9. 1.]]
[[2. 8.]
 [4. 4.]]


In [115]:
np.vstack((a,b)) # Stacking one array above another.

array([[2., 2.],
       [9., 1.],
       [2., 8.],
       [4., 4.]])

In [116]:
np.hstack((a,b)) # Stacking one array beside another

array([[2., 2., 2., 8.],
       [9., 1., 4., 4.]])

In [117]:
h=np.array([[11,12,13,14,15,16],[17,19,23,24,25,34]])
print(h)

[[11 12 13 14 15 16]
 [17 19 23 24 25 34]]


In [121]:
np.hsplit(h,3) # Split "h" into 3

[array([[11, 12],
        [17, 19]]),
 array([[13, 14],
        [23, 24]]),
 array([[15, 16],
        [25, 34]])]

In [122]:
np.hsplit(h,(3,4)) # Split "h" after the third and the fourth column

[array([[11, 12, 13],
        [17, 19, 23]]),
 array([[14],
        [24]]),
 array([[15, 16],
        [25, 34]])]

In [123]:
np.vsplit(h,2) # Splits along vertical axis

[array([[11, 12, 13, 14, 15, 16]]), array([[17, 19, 23, 24, 25, 34]])]

In [127]:
a = np.array([[11,22,33],[44,55,66],[12,14,34]])
a

array([[11, 22, 33],
       [44, 55, 66],
       [12, 14, 34]])

In [128]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [129]:
c = a+b
print(c)

[[12 24 36]
 [45 57 69]
 [13 16 37]]
